language: python
os: linux
jobs:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: xenial
      python: 2.7
    - os: linux
      dist: xenial
      python: 3.5
    - os: linux
      dist: bionic
      python: 2.7
    - os: linux
      dist: bionic
      python: 3.5 
    - os: linux
      dist: bionic
      python: 3.6 
install:
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
