language: python
os: linux
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
install:
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
