language: python
os: linux
jobs:
  include:
    - os: linux
      dist: trusty
      python:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
    - os: linux
      dist: precise
      python:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
    - os: linux
      dist: xenial
      python:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
    - os: linux
      dist: bionic
      python:
        - "2.7"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8"
install:
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
